name: README build

on:
  push:
    branches: ['main']
  workflow_dispatch:

  schedule:
    - cron: '0 */6 * * *'

jobs:
  Release:
    if: |
      github.ref == 'refs/heads/main' &&
      github.event.repository.fork == false &&
      github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    environment: FSI_DEP_Profile
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Install dependencies
        run: npm install

      - name: Generate README file
        run: npm run update-readme
        env:
          OPEN_WEATHER_MAP_KEY: ${{secrets.OPEN_WEATHER_MAP_KEY}}
          MAP_LAT: ${{vars.MAP_LAT}}
          MAP_LON: ${{vars.MAP_LON}}

      - name: Push new README.md
        run: |
          git config user.name ${{vars.COMMIT_NAME}}
          git config user.email ${{secrets.COMMIT_EMAIL}}
          git add README.md package-lock.json
          git diff --quiet && git diff --staged --quiet || git commit -m "[bot] Update README with latest info"
          git push origin main
